version: '3.8'
services:
  db:
    env_file:
      - ./.env
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
    image: postgres:14.1-alpine
    ports:
      - '5433:5432'
    volumes: 
      - db_data:/var/lib/postgresql/data
    container_name: postgres-14.1-alpine-testtask
    restart: always

  seq:
    image: datalust/seq:latest
    ports:
      - '5341:80'
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq_data:/data
    container_name: seq
    restart: always

volumes:
  db_data:
  seq_data: